export const IMAGE_GET_IMAGE_SLIDE = 'IMAGE_GET_IMAGE_SLIDE' 
export const IMAGE_GET_IMAGE_SLIDE_SUCCESS = 'IMAGE_GET_IMAGE_SLIDE_SUCCESS' 
export const IMAGE_GET_IMAGE_SLIDE_FAILURE = 'IMAGE_GET_IMAGE_SLIDE_FAILURE' 