export const MODULES_GET_MODULES = 'MODULES_GET_MODULES' 
export const MODULES_GET_MODULES_SUCCESS = 'MODULES_GET_MODULES_SUCCESS' 
export const MODULES_GET_MODULES_FAILURE = 'MODULES_GET_MODULES_FAILURE' 